"""add_client_ip_and_request_url_to_pricing_quotes

Revision ID: 165b0492d71d
Revises: add_uwm_fields
Create Date: 2025-12-15 01:05:25.296647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165b0492d71d'
down_revision: Union[str, Sequence[str], None] = 'add_uwm_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_quotes', sa.Column('client_ip', sa.String(length=45), nullable=True, comment='Client IP address of the request sender'))
    op.add_column('pricing_quotes', sa.Column('request_url', sa.String(length=500), nullable=True, comment='Full request URL with query parameters'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_quotes', 'request_url')
    op.drop_column('pricing_quotes', 'client_ip')
    # ### end Alembic commands ###
